export const ADMIN_USER_LIST_SUCCESS = "ADMIN_USER_LIST_SUCCESS";
export const ADMIN_USER_LIST_REQUEST = "ADMIN_USER_LIST_REQUEST";
export const ADMIN_USER_LIST_FAILURE = "ADMIN_USER_LIST_FAILURE";
export const ADMIN_USER_LIST_RESET = "ADMIN_USER_LIST_RESET";

export const ADMIN_USER_DELETE_REQUEST = "ADMIN_USER_DELETE_REQUEST";
export const ADMIN_USER_DELETE_SUCCESS = "ADMIN_USER_DELETE_SUCCESS";
export const ADMIN_USER_DELETE_FAILURE = "ADMIN_USER_DELETE_FAILURE";
export const ADMIN_USER_DELETE_RESET = "ADMIN_USER_DELETE_RESET"

export const ADMIN_USER_DETAILS_REQUEST = "ADMIN_USER_DETAILS_REQUEST";
export const ADMIN_USER_DETAILS_SUCCESS = "ADMIN_USER_DETAILS_SUCCESS";
export const ADMIN_USER_DETAILS_FAILURE = "ADMIN_USER_DETAILS_FAILURE";

export const ADMIN_USER_UPDATE_REQUEST = "ADMIN_USER_UPDATE_REQUEST";
export const ADMIN_USER_UPDATE_SUCCESS = "ADMIN_USER_UPDATE_SUCCESS";
export const ADMIN_USER_UPDATE_FAILURE = "ADMIN_USER_UPDATE_FAILURE";
export const ADMIN_USER_UPDATE_RESET = "ADMIN_USER_UPDATE_RESET";

export const ADMIN_PRODUCT_LIST_REQUEST = "ADMIN_PRODUCT_LIST_REQUEST";
export const ADMIN_PRODUCT_LIST_SUCCESS = "ADMIN_PRODUCT_LIST_SUCCESS";
export const ADMIN_PRODUCT_LIST_FAILURE = "ADMIN_PRODUCT_LIST_FAILURE";
export const ADMIN_PRODUCT_LIST_RESET = "ADMIN_PRODUCT_LIST_RESET";

export const ADMIN_PRODUCT_DELETE_REQUEST = "ADMIN_PRODUCT_DELETE_REQUEST";
export const ADMIN_PRODUCT_DELETE_SUCCESS = "ADMIN_PRODUCT_DELETE_SUCCESS";
export const ADMIN_PRODUCT_DELETE_FAILURE = "ADMIN_PRODUCT_DELETE_FAILURE";
export const ADMIN_PRODUCT_DELETE_RESET = "ADMIN_PRODUCT_DELETE_RESET";

export const ADMIN_PRODUCT_DETAILS_REQUEST = "ADMIN_PRODUCT_DETAILS_REQUEST";
export const ADMIN_PRODUCT_DETAILS_SUCCESS = "ADMIN_PRODUCT_DETAILS_SUCCESS";
export const ADMIN_PRODUCT_DETAILS_FAILURE = "ADMIN_PRODUCT_DETAILS_FAILURE";

export const ADMIN_PRODUCT_UPDATE_REQUEST = "ADMIN_PRODUCT_UPDATE_REQUEST";
export const ADMIN_PRODUCT_UPDATE_SUCCESS = "ADMIN_PRODUCT_UPDATE_SUCCESS";
export const ADMIN_PRODUCT_UPDATE_FAILURE = "ADMIN_PRODUCT_UPDATE_FAILURE";
export const ADMIN_PRODUCT_UPDATE_RESET = "ADMIN_PRODUCT_UPDATE_RESET";

export const ADMIN_PRODUCT_CREATE_REQUEST = "ADMIN_PRODUCT_CREATE_REQUEST";
export const ADMIN_PRODUCT_CREATE_SUCCESS = "ADMIN_PRODUCT_CREATE_SUCCESS";
export const ADMIN_PRODUCT_CREATE_FAILURE = "ADMIN_PRODUCT_CREATE_FAILURE";
export const ADMIN_PRODUCT_CREATE_RESET = "ADMIN_PRODUCT_CREATE_RESET";

export const ADMIN_ORDER_LIST_REQUEST = "ADMIN_ORDER_LIST_REQUEST";
export const ADMIN_ORDER_LIST_SUCCESS = "ADMIN_ORDER_LIST_SUCCESS";
export const ADMIN_ORDER_LIST_FAILURE="ADMIN_ORDER_LIST_FAILURE";
export const ADMIN_ORDER_LIST_RESET ="ADMIN_ORDER_LIST_RESET";

export const ADMIN_ORDER_DELIVERED_REQUEST = "ADMIN_ORDER_DELIVERED_REQUEST";
export const ADMIN_ORDER_DELIVERED_SUCCESS = "ADMIN_ORDER_DELIVERED_SUCCESS";
export const ADMIN_ORDER_DELIVERED_FAILURE = "ADMIN_ORDER_DELIVERED_FAILURE";
export const ADMIN_ORDER_DELIVERED_RESET = "ADMIN_ORDER_DELIVERED_RESET"
